spring:
  servlet:
    multipart:
      max-file-size: 10MB      # íŒŒì¼ í•˜ë‚˜ ìµœëŒ€ í¬ê¸°
      max-request-size: 10MB   # ìš”ì²­ ì „ì²´ ìµœëŒ€ í¬ê¸°
  application:
    name: rental

  datasource:
    # 1. ì ‘ì† ì£¼ì†Œì— allowPublicKeyRetrieval=true í•„ìˆ˜! (RSA ë³´ì•ˆ ë¬¸ì œ í•´ê²°)
    url: jdbc:mysql://localhost:3306/neorental_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 0902

  jpa:
    # 2. ìµœì‹  í•˜ì´ë²„ë„¤ì´íŠ¸ìš© ë°©ì–¸ ëª…ì‹œ
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server:
  servlet:
    session:
      timeout: 60m  # ì„¸ì…˜ ì´ˆê¸°í™” ì‹œê°„ì„ 60ë¶„ìœ¼ë¡œ ì„¤ì •

jwt:
  secret: VlwEyVlPKZ6yV9yVlwEyVlPKZ6yV9yVlwEyVlPKZ6yV9yVlwEyVlPKZ6yV9y # ì„ì˜ ì„¤ì •

file:
  upload-dir: /Users/oppenheimer/2026/rentalservice_sprint/rental-images/

# ğŸ‘‡ [ì¶”ê°€] ì›¹ì†Œì¼“ ë§¤í•‘ ê³¼ì •ì„ ìì„¸íˆ ë³´ê¸° ìœ„í•œ ë¡œê·¸ ì„¤ì •
logging:
  level:
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG